Vagrant.configure("2") do |config|
    config.vm.define "wiki" do |wiki|
      wiki.vm.box = "debian/buster64"
      wiki.vm.network "private_network", ip: "192.168.56.30"
      wiki.vm.hostname = "wiki"
    end
    config.vm.define "backup" do |backup|
	backup.vm.box = "debian/buster64"
	backup.vm.network "private_network", ip: "192.168.56.40"
	backup.vm.hostname = "backup"
    end
end